// <auto-generated />
namespace EMMTY_GO_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class emmtygo7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emmtygo7));
        
        string IMigrationMetadata.Id
        {
            get { return "201507231827029_emmtygo7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
