// <auto-generated />
namespace EMMTY_GO_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emmtymr1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emmtymr1));
        
        string IMigrationMetadata.Id
        {
            get { return "201507281724213_emmtymr1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
