// <auto-generated />
namespace EMMTY_GO_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class emmtygo4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emmtygo4));
        
        string IMigrationMetadata.Id
        {
            get { return "201507131832052_emmtygo4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
