//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System.Collections.Generic;
    
    [Table("Aceptadores_Billetes")]
    public class Aceptador_Billetes
    {
        public Aceptador_Billetes()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdAceptador_Billetes { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloAceptador_Billetes { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreAceptador_Billetes { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSAceptador_Billetes { get; set; }
        
        [Required]
        [Display(Name = "Estatus")]
        public bool StatusAceptador_Billetes { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorAceptador_Billetes { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaAceptador_Billetes { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
