//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Aceptadores_Monedas")]
    public class Aceptador_Monedas
    {
        public Aceptador_Monedas()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdAceptador_Monedas { get; set; }

        [Required]
        [Display(Name="Modelo")]
        public string ModeloAceptador_Monedas { get; set; }
        
        [Required]
        [Display(Name = "Nombre")]
        public string NombreAceptador_Monedas { get; set; }
        
        [Required]
        [Display(Name = "Numero de serie")]
        public string NSAceptador_Monedas { get; set; }
        
        [Required]
        [Display(Name = "Estatus")]
        public bool StatusAceptador_Monedas { get; set; }
        
        [Required]
        [Display(Name = "Error")]
        public string ErrorAceptador_Monedas { get; set; }
        
        [Required]
        [Display(Name = "Marca")]
        public string MarcaAceptador_Monedas { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
