//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Cajeros")]
    public partial class Cajero
    {
        public Cajero()
        {
            this.ReportesCajero = new HashSet<ReportesCajero>();
        }


        [Required]
        [Display(Name = "Color")]
        public string ColorCajero { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de entrega")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaEntregaCajero { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de salida")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaSalidaCajero { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Ensamblado")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaEnsambladoCajero { get; set; }

        [Key]
        public int IdCajero { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSCajero { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreCajero { get; set; }

        [Required]
        [Display(Name = "Nombre del Ensamblador")]
        public string NombreEnsamblador { get; set; }

        [Required]
        [Display(Name = "Ubicacion")]
        public string UbicacionCajero { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorCajero { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusCajero { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloCajero { get; set; }

        [Required]
        [Display(Name = "Tipo")]
        public string TipoCajero { get; set; }
        
        public Nullable<int> IdAceptador_Billetes { get; set; }
        public Nullable<int> IdDispensador { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdPC { get; set; }
        public Nullable<int> IdImpresora { get; set; }
        public Nullable<int> IdAceptador_Monedas { get; set; }
        public Nullable<int> IdTarjeta { get; set; }
        public Nullable<int> IdUPS { get; set; }
        public Nullable<int> IdScanner { get; set; }
        public Nullable<int> IdMonitor { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdToneleroA { get; set; }
        public Nullable<int> IdToneleroB { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Actual")]
        public int EfectivoActual { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Dispensado")]
        public int EfectivoDispensado { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Inicial")]
        public int EfectivoInicial { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Nivel bajo de Efectivo")]
        public int NivelBajoEfectivo { get; set; }

        public bool RowUpdate { get; set; }
        public bool EnabledNotification { get; set; }
        public bool Online { get; set; }
        public string AtmUserId { get; set; }

        [Display(Name = "Aceptador de Billetes")]
        public virtual Aceptador_Billetes Aceptador_Billetes { get; set; }

        [Display(Name = "Aceptador de Monedas")]
        public virtual Aceptador_Monedas Aceptador_Monedas { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Dispensador Dispensador { get; set; }
        public virtual Impresora Impresora { get; set; }
        public virtual Monitor Monitor { get; set; }
        public virtual PC PC { get; set; }
        public virtual Scanner Scanner { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }

        [DisplayName("Tonelero A")]
        public virtual ToneleroA ToneleroA { get; set; }

        [DisplayName("Tonelero B")]
        public virtual ToneleroB ToneleroB { get; set; }
        public virtual UPS UPS { get; set; }
        public virtual ICollection<ReportesCajero> ReportesCajero { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
    }
}
