//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System.Collections.Generic;


    [Table("Clientes")]
    public partial class Cliente
    {
        public Cliente()
        {
            Cajeros = new HashSet<Cajero>();
            Users = new HashSet<ApplicationUser>();
        }
    
        [Key]
        public int IdCliente { get; set; }

        [Required]
        [Display(Name = "Estatus de licencia")]
        public string LicenciaStatus { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreCliente { get; set; }

        [Required]
        [Display(Name = "Tipo de Razon social")]
        public string TipoCliente { get; set; }
    
        public virtual ICollection<ApplicationUser> Users { get; set; }
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
