//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;


    [Table("Dispensadores")]
    public partial class Dispensador
    {
        public Dispensador()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdDispensador { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Actual")]
        public int EfectivoActualDispensador { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Dispensado")]
        public int EfectivoDispensadoDispensador { get; set; }

        [Required]
        [Range(Int32.MinValue, Int32.MaxValue)]
        [Display(Name = "Efectivo Inicial")]
        public int EfectivoInicialDispensador { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloDispensador { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSDispensador { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusDispensador { get; set; }

        [Required]
        [Display(Name = "Denominacion")]
        public string TipoBillete { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorDispensador { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaDispensador { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreDispensador { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
