//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Impresoras")]
    public partial class Impresora
    {
        public Impresora()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdImpresora { get; set; }
        
        [Required]
        [Display(Name = "Numero de serie")]
        public string NSImpresora { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreImpresora { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloImpresora { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusImpresora { get; set; }

        [Required]
        [Display(Name = "Papel")]
        public bool PapelImpresora { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorImpresora { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaImpresora { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
