//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Monitores")]
    public partial class Monitor
    {
        public Monitor()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdMonitor { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaMonitor { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloMonitor { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreMonitor { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSMonitor { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusMonitor { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorMonitor { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
