//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;


    [Table("PCes")]
    public partial class PC
    {
        public PC()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdPC { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaPC { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloPC { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombrePC { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSPC { get; set; }

        [Required]
        [Display(Name = "Sistema Operativo")]
        public string OSPC { get; set; }

        [Required]
        [Display(Name = "Status")]
        public bool StatusPC { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorPC { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
