//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;


    [Table("ReportesCajeros")]
    public partial class ReportesCajero
    {
        public Nullable<int> IdReporte { get; set; }
        public Nullable<int> IdCajero { get; set; }
        
        [Key]
        public int IdReporteCajero { get; set; }
    
        public virtual Cajero Cajeros { get; set; }
        public virtual Reporte Reportes { get; set; }
    }
}
