//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;


    [Table("Reportes")]
    public partial class Reporte
    {
        public Reporte()
        {
            this.ReportesCajero = new HashSet<ReportesCajero>();
        }
    
        [Key]
        public int IdReporte { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha del reporte")]
        public DateTime FechaReporte { get; set; }

        [Required]
        [Display(Name = "Reporte Correctivo")]
        public string CorrectivoReporte { get; set; }

        [Required]
        [Display(Name = "Reporte Preventivo")]
        public string PreventivoReporte { get; set; }

        [Required]
        [Display(Name = "Tecnico")]
        public string TecnicoReporte { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreReporte { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSReporte { get; set; }
    
        public virtual ICollection<ReportesCajero> ReportesCajero { get; set; }
    }
}
