//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Scanners")]
    public partial class Scanner
    {
        public Scanner()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdScanner { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaScanner { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloScanner { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreScanner { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSScanner { get; set; }

        [Required]
        [Display(Name = "Status")]
        public bool StatusScanner { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorScanner { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
