//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Sucursales")]
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdSucursal { get; set; }

        [Required]
        [Display(Name = "Supervisor de cajeros")]
        public string SupervisorCajero { get; set; }

        [Required]
        [Display(Name = "Empresa")]
        public string EmpresaSucursal { get; set; }

        [Required]
        [Display(Name = "Telefono")]
        public int TelefonoSucursal { get; set; }

        [Required]
        [Display(Name = "Gerente")]
        public string GerenteSucursal { get; set; }

        [Required]
        [Display(Name = "Direccion")]
        public string DireccionSucursal { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreSucursal { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
