//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("Tarjetas")]
    public partial class Tarjeta
    {
        public Tarjeta()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdTarjeta { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloTarjeta { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSTarjeta { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusTarjeta { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorTarjeta { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaTarjeta { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreTarjeta { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
