//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EMMTY_GO_WEB.Object;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("TonelerosA")]
    public partial class ToneleroA : ITonelero
    {
        public ToneleroA()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdToneleroA { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreTonelero { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloTonelero { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSTonelero { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusTonelero { get; set; }

        [Required]
        [Display(Name = "Denominacion Moneda")]
        public string TipoMoneda { get; set; }

        [Required]
        [Display(Name = "Efectivo Actual")]
        [Range(Int32.MinValue, Int32.MaxValue)]
        public int EfectivoActualTonelero { get; set; }

        [Required]
        [Display(Name = "Efectivo Dispensado")]
        [Range(Int32.MinValue, Int32.MaxValue)]
        public int EfectivoDispensadoTonelero { get; set; }

        [Required]
        [Display(Name = "Efectivo Inicial")]
        [Range(Int32.MinValue, Int32.MaxValue)]
        public int EfectivoInicialTonelero { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorTonelero { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaTonelero { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }

}
