//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMMTY_GO_WEB.Models
{
    using System;
    using System.Collections.Generic;

    [Table("UPes")]
    public partial class UPS
    {
        public UPS()
        {
            this.Cajeros = new HashSet<Cajero>();
        }
    
        [Key]
        public int IdUPS { get; set; }

        [Required]
        [Display(Name = "Marca")]
        public string MarcaUPS { get; set; }

        [Required]
        [Display(Name = "Modelo")]
        public string ModeloUPS { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string NombreUPS { get; set; }

        [Required]
        [Display(Name = "Numero de serie")]
        public string NSUPS { get; set; }

        [Required]
        [Display(Name = "Estatus")]
        public bool StatusUPS { get; set; }

        [Required]
        [Display(Name = "Error")]
        public string ErrorUPS { get; set; }
    
        public virtual ICollection<Cajero> Cajeros { get; set; }
    }
}
